//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.arm.hud.gov/", ConfigurationName="ServiceReference1.ArmService")]
    public interface ArmService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.pingResponse> pingAsync(ServiceReference1.ping1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getReferenceResponse> getReferenceAsync(ServiceReference1.getReference1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getAllReferenceItemsResponse> getAllReferenceItemsAsync(ServiceReference1.getAllReferenceItems1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getReferenceGroupNamesResponse> getReferenceGroupNamesAsync(ServiceReference1.getReferenceGroupNames1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.postSubmissionResponse1> postSubmissionAsync(ServiceReference1.postSubmission1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.postSubmissionResponse1> postAgencyDataAsync(ServiceReference1.postAgencyData1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.postSubmissionResponse1> postCounselorDataAsync(ServiceReference1.postCounselorData1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.postSubmissionResponse1> postClientDataAsync(ServiceReference1.postClientData1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.postSubmissionResponse1> postForm9902DataAsync(ServiceReference1.postForm9902Data1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getSubmissionInfoResponse1> getSubmissionInfoAsync(ServiceReference1.getSubmissionInfo1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getDetailedErrorMessageResponse1> getDetailedErrorMessageAsync(ServiceReference1.getDetailedErrorMessage1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task refreshReferenceItemCacheAsync(ServiceReference1.refreshReferenceItemCache1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task refreshAllReferenceItemsInCacheAsync(ServiceReference1.refreshAllReferenceItemsInCache1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class ping
    {
        
        private int agcHcsIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int agcHcsId
        {
            get
            {
                return this.agcHcsIdField;
            }
            set
            {
                this.agcHcsIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ping1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.ping ping;
        
        public ping1()
        {
        }
        
        public ping1(ServiceReference1.ping ping)
        {
            this.ping = ping;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pingResponse", Namespace="http://service.arm.hud.gov/", Order=0)]
        public string pingResponse1;
        
        public pingResponse()
        {
        }
        
        public pingResponse(string pingResponse1)
        {
            this.pingResponse1 = pingResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class getReference
    {
        
        private int agcHcsIdField;
        
        private int referenceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int agcHcsId
        {
            get
            {
                return this.agcHcsIdField;
            }
            set
            {
                this.agcHcsIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int referenceId
        {
            get
            {
                return this.referenceIdField;
            }
            set
            {
                this.referenceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class referenceItem
    {
        
        private int idField;
        
        private string longDescField;
        
        private string nameField;
        
        private string shortDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string longDesc
        {
            get
            {
                return this.longDescField;
            }
            set
            {
                this.longDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string shortDesc
        {
            get
            {
                return this.shortDescField;
            }
            set
            {
                this.shortDescField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReference1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.getReference getReference;
        
        public getReference1()
        {
        }
        
        public getReference1(ServiceReference1.getReference getReference)
        {
            this.getReference = getReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReferenceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReferenceResponse", Namespace="http://service.arm.hud.gov/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("referenceItem", IsNullable=false)]
        public ServiceReference1.referenceItem[] getReferenceResponse1;
        
        public getReferenceResponse()
        {
        }
        
        public getReferenceResponse(ServiceReference1.referenceItem[] getReferenceResponse1)
        {
            this.getReferenceResponse1 = getReferenceResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class getAllReferenceItems
    {
        
        private int agcHcsIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int agcHcsId
        {
            get
            {
                return this.agcHcsIdField;
            }
            set
            {
                this.agcHcsIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class referenceItemGroup
    {
        
        private int groupIdField;
        
        private referenceItem[] referenceItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int groupId
        {
            get
            {
                return this.groupIdField;
            }
            set
            {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referenceItem", Order=1)]
        public referenceItem[] referenceItem
        {
            get
            {
                return this.referenceItemField;
            }
            set
            {
                this.referenceItemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllReferenceItems1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.getAllReferenceItems getAllReferenceItems;
        
        public getAllReferenceItems1()
        {
        }
        
        public getAllReferenceItems1(ServiceReference1.getAllReferenceItems getAllReferenceItems)
        {
            this.getAllReferenceItems = getAllReferenceItems;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllReferenceItemsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllReferenceItemsResponse", Namespace="http://service.arm.hud.gov/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("referenceItemGroup", IsNullable=false)]
        public ServiceReference1.referenceItemGroup[] getAllReferenceItemsResponse1;
        
        public getAllReferenceItemsResponse()
        {
        }
        
        public getAllReferenceItemsResponse(ServiceReference1.referenceItemGroup[] getAllReferenceItemsResponse1)
        {
            this.getAllReferenceItemsResponse1 = getAllReferenceItemsResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class getReferenceGroupNames
    {
        
        private int agcHcsIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int agcHcsId
        {
            get
            {
                return this.agcHcsIdField;
            }
            set
            {
                this.agcHcsIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class referenceGroup
    {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReferenceGroupNames1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.getReferenceGroupNames getReferenceGroupNames;
        
        public getReferenceGroupNames1()
        {
        }
        
        public getReferenceGroupNames1(ServiceReference1.getReferenceGroupNames getReferenceGroupNames)
        {
            this.getReferenceGroupNames = getReferenceGroupNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReferenceGroupNamesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReferenceGroupNamesResponse", Namespace="http://service.arm.hud.gov/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("referenceGroup", IsNullable=false)]
        public ServiceReference1.referenceGroup[] getReferenceGroupNamesResponse1;
        
        public getReferenceGroupNamesResponse()
        {
        }
        
        public getReferenceGroupNamesResponse(ServiceReference1.referenceGroup[] getReferenceGroupNamesResponse1)
        {
            this.getReferenceGroupNamesResponse1 = getReferenceGroupNamesResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class postSubmission
    {
        
        private submissionHeader submissionHeaderField;
        
        private string submissionDataEncodingField;
        
        private byte[] submissionDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public submissionHeader submissionHeader
        {
            get
            {
                return this.submissionHeaderField;
            }
            set
            {
                this.submissionHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string submissionDataEncoding
        {
            get
            {
                return this.submissionDataEncodingField;
            }
            set
            {
                this.submissionDataEncodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] submissionData
        {
            get
            {
                return this.submissionDataField;
            }
            set
            {
                this.submissionDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class submissionHeader
    {
        
        private int agcHcsIdField;
        
        private string agcNameField;
        
        private int systemNameField;
        
        private int subFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int agcHcsId
        {
            get
            {
                return this.agcHcsIdField;
            }
            set
            {
                this.agcHcsIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string agcName
        {
            get
            {
                return this.agcNameField;
            }
            set
            {
                this.agcNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int systemName
        {
            get
            {
                return this.systemNameField;
            }
            set
            {
                this.systemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int subFlag
        {
            get
            {
                return this.subFlagField;
            }
            set
            {
                this.subFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class postSubmissionResponse
    {
        
        private long submissionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long submissionId
        {
            get
            {
                return this.submissionIdField;
            }
            set
            {
                this.submissionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postSubmission1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.postSubmission postSubmission;
        
        public postSubmission1()
        {
        }
        
        public postSubmission1(ServiceReference1.postSubmission postSubmission)
        {
            this.postSubmission = postSubmission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postSubmissionResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.postSubmissionResponse postSubmissionResponse;
        
        public postSubmissionResponse1()
        {
        }
        
        public postSubmissionResponse1(ServiceReference1.postSubmissionResponse postSubmissionResponse)
        {
            this.postSubmissionResponse = postSubmissionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class postAgencyData
    {
        
        private submissionHeader50 submissionHeader50Field;
        
        private string submissionDataEncodingField;
        
        private byte[] submissionDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("submissionHeader5.0", Order=0)]
        public submissionHeader50 submissionHeader50
        {
            get
            {
                return this.submissionHeader50Field;
            }
            set
            {
                this.submissionHeader50Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string submissionDataEncoding
        {
            get
            {
                return this.submissionDataEncodingField;
            }
            set
            {
                this.submissionDataEncodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] submissionData
        {
            get
            {
                return this.submissionDataField;
            }
            set
            {
                this.submissionDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class submissionHeader50
    {
        
        private int agcHcsIdField;
        
        private string agcNameField;
        
        private int fiscalYearIdField;
        
        private int cmsVendorIdField;
        
        private string cmsPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int agcHcsId
        {
            get
            {
                return this.agcHcsIdField;
            }
            set
            {
                this.agcHcsIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string agcName
        {
            get
            {
                return this.agcNameField;
            }
            set
            {
                this.agcNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int fiscalYearId
        {
            get
            {
                return this.fiscalYearIdField;
            }
            set
            {
                this.fiscalYearIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int cmsVendorId
        {
            get
            {
                return this.cmsVendorIdField;
            }
            set
            {
                this.cmsVendorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string cmsPassword
        {
            get
            {
                return this.cmsPasswordField;
            }
            set
            {
                this.cmsPasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postAgencyData1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.postAgencyData postAgencyData;
        
        public postAgencyData1()
        {
        }
        
        public postAgencyData1(ServiceReference1.postAgencyData postAgencyData)
        {
            this.postAgencyData = postAgencyData;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class postCounselorData
    {
        
        private submissionHeader50 submissionHeader50Field;
        
        private string submissionDataEncodingField;
        
        private byte[] submissionDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("submissionHeader5.0", Order=0)]
        public submissionHeader50 submissionHeader50
        {
            get
            {
                return this.submissionHeader50Field;
            }
            set
            {
                this.submissionHeader50Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string submissionDataEncoding
        {
            get
            {
                return this.submissionDataEncodingField;
            }
            set
            {
                this.submissionDataEncodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] submissionData
        {
            get
            {
                return this.submissionDataField;
            }
            set
            {
                this.submissionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postCounselorData1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.postCounselorData postCounselorData;
        
        public postCounselorData1()
        {
        }
        
        public postCounselorData1(ServiceReference1.postCounselorData postCounselorData)
        {
            this.postCounselorData = postCounselorData;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class postClientData
    {
        
        private submissionHeader50 submissionHeader50Field;
        
        private string submissionDataEncodingField;
        
        private byte[] submissionDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("submissionHeader5.0", Order=0)]
        public submissionHeader50 submissionHeader50
        {
            get
            {
                return this.submissionHeader50Field;
            }
            set
            {
                this.submissionHeader50Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string submissionDataEncoding
        {
            get
            {
                return this.submissionDataEncodingField;
            }
            set
            {
                this.submissionDataEncodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] submissionData
        {
            get
            {
                return this.submissionDataField;
            }
            set
            {
                this.submissionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postClientData1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.postClientData postClientData;
        
        public postClientData1()
        {
        }
        
        public postClientData1(ServiceReference1.postClientData postClientData)
        {
            this.postClientData = postClientData;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class postForm9902Data
    {
        
        private submissionHeader50 submissionHeader50Field;
        
        private string submissionDataEncodingField;
        
        private byte[] submissionDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("submissionHeader5.0", Order=0)]
        public submissionHeader50 submissionHeader50
        {
            get
            {
                return this.submissionHeader50Field;
            }
            set
            {
                this.submissionHeader50Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string submissionDataEncoding
        {
            get
            {
                return this.submissionDataEncodingField;
            }
            set
            {
                this.submissionDataEncodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] submissionData
        {
            get
            {
                return this.submissionDataField;
            }
            set
            {
                this.submissionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postForm9902Data1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.postForm9902Data postForm9902Data;
        
        public postForm9902Data1()
        {
        }
        
        public postForm9902Data1(ServiceReference1.postForm9902Data postForm9902Data)
        {
            this.postForm9902Data = postForm9902Data;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class getSubmissionInfo
    {
        
        private int agcHcsIdField;
        
        private long submissionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int agcHcsId
        {
            get
            {
                return this.agcHcsIdField;
            }
            set
            {
                this.agcHcsIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long submissionId
        {
            get
            {
                return this.submissionIdField;
            }
            set
            {
                this.submissionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class getSubmissionInfoResponse
    {
        
        private System.DateTime statusDateField;
        
        private string statusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime statusDate
        {
            get
            {
                return this.statusDateField;
            }
            set
            {
                this.statusDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string statusMessage
        {
            get
            {
                return this.statusMessageField;
            }
            set
            {
                this.statusMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSubmissionInfo1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.getSubmissionInfo getSubmissionInfo;
        
        public getSubmissionInfo1()
        {
        }
        
        public getSubmissionInfo1(ServiceReference1.getSubmissionInfo getSubmissionInfo)
        {
            this.getSubmissionInfo = getSubmissionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSubmissionInfoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.getSubmissionInfoResponse getSubmissionInfoResponse;
        
        public getSubmissionInfoResponse1()
        {
        }
        
        public getSubmissionInfoResponse1(ServiceReference1.getSubmissionInfoResponse getSubmissionInfoResponse)
        {
            this.getSubmissionInfoResponse = getSubmissionInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class getDetailedErrorMessage
    {
        
        private int agcHcsIdField;
        
        private long submissionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int agcHcsId
        {
            get
            {
                return this.agcHcsIdField;
            }
            set
            {
                this.agcHcsIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long submissionId
        {
            get
            {
                return this.submissionIdField;
            }
            set
            {
                this.submissionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class getDetailedErrorMessageResponse
    {
        
        private System.DateTime statusDateField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime statusDate
        {
            get
            {
                return this.statusDateField;
            }
            set
            {
                this.statusDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetailedErrorMessage1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.getDetailedErrorMessage getDetailedErrorMessage;
        
        public getDetailedErrorMessage1()
        {
        }
        
        public getDetailedErrorMessage1(ServiceReference1.getDetailedErrorMessage getDetailedErrorMessage)
        {
            this.getDetailedErrorMessage = getDetailedErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetailedErrorMessageResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.getDetailedErrorMessageResponse getDetailedErrorMessageResponse;
        
        public getDetailedErrorMessageResponse1()
        {
        }
        
        public getDetailedErrorMessageResponse1(ServiceReference1.getDetailedErrorMessageResponse getDetailedErrorMessageResponse)
        {
            this.getDetailedErrorMessageResponse = getDetailedErrorMessageResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class refreshReferenceItemCache
    {
        
        private int agcHcsIdField;
        
        private int referenceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int agcHcsId
        {
            get
            {
                return this.agcHcsIdField;
            }
            set
            {
                this.agcHcsIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int referenceId
        {
            get
            {
                return this.referenceIdField;
            }
            set
            {
                this.referenceIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class refreshReferenceItemCache1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.refreshReferenceItemCache refreshReferenceItemCache;
        
        public refreshReferenceItemCache1()
        {
        }
        
        public refreshReferenceItemCache1(ServiceReference1.refreshReferenceItemCache refreshReferenceItemCache)
        {
            this.refreshReferenceItemCache = refreshReferenceItemCache;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.arm.hud.gov/")]
    public partial class refreshAllReferenceItemsInCache
    {
        
        private int agcHcsIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int agcHcsId
        {
            get
            {
                return this.agcHcsIdField;
            }
            set
            {
                this.agcHcsIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class refreshAllReferenceItemsInCache1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.arm.hud.gov/", Order=0)]
        public ServiceReference1.refreshAllReferenceItemsInCache refreshAllReferenceItemsInCache;
        
        public refreshAllReferenceItemsInCache1()
        {
        }
        
        public refreshAllReferenceItemsInCache1(ServiceReference1.refreshAllReferenceItemsInCache refreshAllReferenceItemsInCache)
        {
            this.refreshAllReferenceItemsInCache = refreshAllReferenceItemsInCache;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ArmServiceChannel : ServiceReference1.ArmService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ArmServiceClient : System.ServiceModel.ClientBase<ServiceReference1.ArmService>, ServiceReference1.ArmService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ArmServiceClient() : 
                base(ArmServiceClient.GetDefaultBinding(), ArmServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ArmServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArmServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ArmServiceClient.GetBindingForEndpoint(endpointConfiguration), ArmServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArmServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ArmServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArmServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ArmServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArmServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.pingResponse> ServiceReference1.ArmService.pingAsync(ServiceReference1.ping1 request)
        {
            return base.Channel.pingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.pingResponse> pingAsync(ServiceReference1.ping ping)
        {
            ServiceReference1.ping1 inValue = new ServiceReference1.ping1();
            inValue.ping = ping;
            return ((ServiceReference1.ArmService)(this)).pingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getReferenceResponse> ServiceReference1.ArmService.getReferenceAsync(ServiceReference1.getReference1 request)
        {
            return base.Channel.getReferenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getReferenceResponse> getReferenceAsync(ServiceReference1.getReference getReference)
        {
            ServiceReference1.getReference1 inValue = new ServiceReference1.getReference1();
            inValue.getReference = getReference;
            return ((ServiceReference1.ArmService)(this)).getReferenceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getAllReferenceItemsResponse> ServiceReference1.ArmService.getAllReferenceItemsAsync(ServiceReference1.getAllReferenceItems1 request)
        {
            return base.Channel.getAllReferenceItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getAllReferenceItemsResponse> getAllReferenceItemsAsync(ServiceReference1.getAllReferenceItems getAllReferenceItems)
        {
            ServiceReference1.getAllReferenceItems1 inValue = new ServiceReference1.getAllReferenceItems1();
            inValue.getAllReferenceItems = getAllReferenceItems;
            return ((ServiceReference1.ArmService)(this)).getAllReferenceItemsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getReferenceGroupNamesResponse> ServiceReference1.ArmService.getReferenceGroupNamesAsync(ServiceReference1.getReferenceGroupNames1 request)
        {
            return base.Channel.getReferenceGroupNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getReferenceGroupNamesResponse> getReferenceGroupNamesAsync(ServiceReference1.getReferenceGroupNames getReferenceGroupNames)
        {
            ServiceReference1.getReferenceGroupNames1 inValue = new ServiceReference1.getReferenceGroupNames1();
            inValue.getReferenceGroupNames = getReferenceGroupNames;
            return ((ServiceReference1.ArmService)(this)).getReferenceGroupNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.postSubmissionResponse1> ServiceReference1.ArmService.postSubmissionAsync(ServiceReference1.postSubmission1 request)
        {
            return base.Channel.postSubmissionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.postSubmissionResponse1> postSubmissionAsync(ServiceReference1.postSubmission postSubmission)
        {
            ServiceReference1.postSubmission1 inValue = new ServiceReference1.postSubmission1();
            inValue.postSubmission = postSubmission;
            return ((ServiceReference1.ArmService)(this)).postSubmissionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.postSubmissionResponse1> ServiceReference1.ArmService.postAgencyDataAsync(ServiceReference1.postAgencyData1 request)
        {
            return base.Channel.postAgencyDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.postSubmissionResponse1> postAgencyDataAsync(ServiceReference1.postAgencyData postAgencyData)
        {
            ServiceReference1.postAgencyData1 inValue = new ServiceReference1.postAgencyData1();
            inValue.postAgencyData = postAgencyData;
            return ((ServiceReference1.ArmService)(this)).postAgencyDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.postSubmissionResponse1> ServiceReference1.ArmService.postCounselorDataAsync(ServiceReference1.postCounselorData1 request)
        {
            return base.Channel.postCounselorDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.postSubmissionResponse1> postCounselorDataAsync(ServiceReference1.postCounselorData postCounselorData)
        {
            ServiceReference1.postCounselorData1 inValue = new ServiceReference1.postCounselorData1();
            inValue.postCounselorData = postCounselorData;
            return ((ServiceReference1.ArmService)(this)).postCounselorDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.postSubmissionResponse1> ServiceReference1.ArmService.postClientDataAsync(ServiceReference1.postClientData1 request)
        {
            return base.Channel.postClientDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.postSubmissionResponse1> postClientDataAsync(ServiceReference1.postClientData postClientData)
        {
            ServiceReference1.postClientData1 inValue = new ServiceReference1.postClientData1();
            inValue.postClientData = postClientData;
            return ((ServiceReference1.ArmService)(this)).postClientDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.postSubmissionResponse1> ServiceReference1.ArmService.postForm9902DataAsync(ServiceReference1.postForm9902Data1 request)
        {
            return base.Channel.postForm9902DataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.postSubmissionResponse1> postForm9902DataAsync(ServiceReference1.postForm9902Data postForm9902Data)
        {
            ServiceReference1.postForm9902Data1 inValue = new ServiceReference1.postForm9902Data1();
            inValue.postForm9902Data = postForm9902Data;
            return ((ServiceReference1.ArmService)(this)).postForm9902DataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getSubmissionInfoResponse1> ServiceReference1.ArmService.getSubmissionInfoAsync(ServiceReference1.getSubmissionInfo1 request)
        {
            return base.Channel.getSubmissionInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getSubmissionInfoResponse1> getSubmissionInfoAsync(ServiceReference1.getSubmissionInfo getSubmissionInfo)
        {
            ServiceReference1.getSubmissionInfo1 inValue = new ServiceReference1.getSubmissionInfo1();
            inValue.getSubmissionInfo = getSubmissionInfo;
            return ((ServiceReference1.ArmService)(this)).getSubmissionInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getDetailedErrorMessageResponse1> ServiceReference1.ArmService.getDetailedErrorMessageAsync(ServiceReference1.getDetailedErrorMessage1 request)
        {
            return base.Channel.getDetailedErrorMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getDetailedErrorMessageResponse1> getDetailedErrorMessageAsync(ServiceReference1.getDetailedErrorMessage getDetailedErrorMessage)
        {
            ServiceReference1.getDetailedErrorMessage1 inValue = new ServiceReference1.getDetailedErrorMessage1();
            inValue.getDetailedErrorMessage = getDetailedErrorMessage;
            return ((ServiceReference1.ArmService)(this)).getDetailedErrorMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ServiceReference1.ArmService.refreshReferenceItemCacheAsync(ServiceReference1.refreshReferenceItemCache1 request)
        {
            return base.Channel.refreshReferenceItemCacheAsync(request);
        }
        
        public System.Threading.Tasks.Task refreshReferenceItemCacheAsync(ServiceReference1.refreshReferenceItemCache refreshReferenceItemCache)
        {
            ServiceReference1.refreshReferenceItemCache1 inValue = new ServiceReference1.refreshReferenceItemCache1();
            inValue.refreshReferenceItemCache = refreshReferenceItemCache;
            return ((ServiceReference1.ArmService)(this)).refreshReferenceItemCacheAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ServiceReference1.ArmService.refreshAllReferenceItemsInCacheAsync(ServiceReference1.refreshAllReferenceItemsInCache1 request)
        {
            return base.Channel.refreshAllReferenceItemsInCacheAsync(request);
        }
        
        public System.Threading.Tasks.Task refreshAllReferenceItemsInCacheAsync(ServiceReference1.refreshAllReferenceItemsInCache refreshAllReferenceItemsInCache)
        {
            ServiceReference1.refreshAllReferenceItemsInCache1 inValue = new ServiceReference1.refreshAllReferenceItemsInCache1();
            inValue.refreshAllReferenceItemsInCache = refreshAllReferenceItemsInCache;
            return ((ServiceReference1.ArmService)(this)).refreshAllReferenceItemsInCacheAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ArmServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ArmServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/ARM/ARM/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ArmServiceClient.GetBindingForEndpoint(EndpointConfiguration.ArmServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ArmServiceClient.GetEndpointAddress(EndpointConfiguration.ArmServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ArmServiceImplPort,
        }
    }
}
